### ISSUE TITLE
[scrum] 2020-03-31 미세먼지 5조 스크럼

### ISSUE THREAD

**Issue by seungdeng17** [codesquad-member-2020/dust-5#26]
- 스크럼 양식
  - 어제 한 일
  - 오늘 할 일
  - 컨디션
  - 고민되는 점

**Comment by seungdeng17** [comment]
### 어제 한 일
- 미세먼지 앱 기본 html css 작성
- 미세먼지 탭 MVC 구조 작성
- 데모 페이지

### 오늘 할 일
- 미세먼지 등급에 따라서 배경 색 변화
- rAF 공부
- 예보 탭 html css 작성

### 컨디션
- 계속 새벽까지 작업을 하니 피로가 많이 누적된 것 같아요. 컨디션 관리 하겠습니다.

### 고민되는 점
- 작업 중인 화면이 모바일에서 똑같은 비율로 보여질 수 있을지 자신할 수 없다!!

**Comment by moonelysian** [comment]
### 어제한 일
- 공공 api 가져오는 법 알아보기
- 필요한 데이터만 넣을 수 있게 가공하기

### 오늘 할 일
- 데이터 선별
- 리팩토링

### 컨디션
이상하게 무릎이 아프다

### 고민되는 점
- json key 이름이 너무 별로여서 바꾸고싶은데 바꾸는 방법 모르겠음

**Comment by Hyune-c** [comment]
### 어제 한 일
  - AWS 배포 
  - 미세먼지 앱 목업 API 구현 (/forecast/dustStatus)
### 오늘 할 일
  - GPS 정보를 TM 정보로 전환
  - TM 정보를 기반으로 측정소 정보 가져오기
### 컨디션
  - 양호
### 고민되는 점
  - 기상청에서 오는 데이터를 어떻게 정제하면 좋을까

**Comment by delmaSong** [comment]
### 어제 한 일
- 미세먼지 화면 기능 구현
- 모델 생성 

### 오늘 할 일
- 테이블뷰 구현
- 서버에서 데이터 받아오기

### 컨디션
- 눈아픔ㅠ

### 고민되는 점
- 서버에 데이터 요청하는 애들을 어떤 기능으로 얼마만큼 쪼갤까?
