### ISSUE TITLE
[scrum] 2020-04-01 미세먼지 5조 스크럼

### ISSUE THREAD

**Issue by seungdeng17** [codesquad-member-2020/dust-5#40]
- 스크럼 양식
  - 어제 한 일
  - 오늘 할 일
  - 컨디션
  - 고민되는 점

**Comment by seungdeng17** [comment]
### 어제 한 일
- 미세먼지 등급에 따라서 배경 색 변화
- 예보 탭 html css 작성
- 수 많은 버그 수정

### 오늘 할 일
- 예보 탭 프로토타입 구현
- 제공 받은 프로젝트 api 테스트

### 컨디션
- 좋아요

### 고민되는 점
- 아름다운 구조를 짜기 위해 노력하지만 스파게티행

**Comment by delmaSong** [comment]
### 어제 한 일
- 미세먼지 화면 속 테이블뷰의 셀이 동적으로 조정되도록 코드 추가
- 셀 재사용 문제 우선순위 줘서 해결
- 테이블뷰 스크롤시 첫번째 셀 인식되도록 함
- 현재 위치 기반 위도,경도 찾는 기능 추가
- 서버에 리퀘스트 날리고 인코드 디코드 할 놈들 추가


### 오늘 할 일
- 위,경도 정보 담아 리퀘스트 보내기
- 받아온 데이터를 기반으로 뷰 업데이트
- SOLID 동영상 오전에 시청하기
- 오후에는 수업

### 컨디션
- 기분 좋아요 눈은 뻑뻑 

### 고민되는 점
- PR 단위를 너무 크게 쪼갰나 싶기도 함 ㅎ 
- scrollDidEnding() 인가 여기서 스크롤 움직이고 상단의 놈을 인식하도록 했는데.. 쨌든 맨 위의 셀의 데이터를 알아야 하잖아? 근데 여기 위치는 테이블뷰고,.. 바깥에 데이터 조정해줘야하는건 뷰컨인데 노티를 보낸다치는데 scollDidEnding() 이 메소드는 스크롤 쫌만되도 와르르 실행되는데 좋은 방법일까 이게? 고민됨

**Comment by moonelysian** [comment]
**어제 한 일**
- 리팩토링의 연속

**오늘 할 일**
- 오늘도 뚠뚠 리팩토링 뚠뚠
- 예외처리??
- 수업 듣기

**컨디션**
- 점심에 초밥 먹기로 해서 매우 행복

**고민 되는 점**
- json 잘 가져와지는데 사실 이렇게 가져오는게 맞나 싶다ㅜ

**Comment by Hyune-c** [comment]
### 어제 한 일
- kakao api 를 통해 WGS84 좌표를 TM 좌표로 전환합니다.
- 기상청 API 에서 TM 좌표를 통해 가장 가까운 측정소를 찾아옵니다.
- 가장 가까운 측정소로부터 미세먼지 정보를 가져옵니다.
### 오늘 할 일
- 리팩토링
- 테스트 코드 생각해보기
### 컨디션
양호
### 고민되는 점
json 다루는게 헷갈리고 힘드네요.
